sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

env:
  global:
    - PROFILE=cloud

branches:
  only:
    - master

before_install:
  - docker version
  - docker info

install:
  - ./mvnw --settings cloud-settings.xml clean install -P$PROFILE

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export APP=sky233/web-flux
  - if [ "$PROFILE" == "cloud" ]; then
  - docker build -t $APP ./target/docker
    fi
  - docker images
  - docker push $APP